export const profileSettingObj = {
  settingBtn: ".dashboard-menu-left > :nth-child(3) > a > span",
  headingProfilesetting: ".frt-date > p",
  patientFullName: 'input[name$="am_first_name"]',
  patientDateofBirth: 'input[name$="am_age"]',
  patientGender: 'input[name$="am_gender"]',
  patientOccupation: 'input[name$="am_occupation"]',
  patientBloodGroup: 'input[name$="am_blood_group"]',
  patientHeight: 'input[name$="am_height"]',
  patientWeight: 'input[name$="am_weight"]',
  saveProfileBtn: ".dc-btn",
  saveProfileBtnDC: ".frt-save-button",
  accountBtn: ".dc-tabstitle > :nth-child(2) > a",
  accountSettingHeading: ".frt-date > p",
  patientUsername: 'input[name$="frtusername"]',
  patientEmail: "fieldset > :nth-child(2) > .form-control",
  patientPhoneNumber: "#frt-phone-number",
  saveAccountBtn: "",
  drSideHeading: ".frt-appt-title",
  drSideSettingBtn: ".dashboard-menu-left > :nth-child(5) > a",

  doctorFirstName: 'input[name$="am_first_name"]',
  doctorLastName: 'input[name$="am_last_name"]',
  doctorGender: "#am_gender",
  DrPrice: 'input[name$="am_starting_price"]',
  doctorPhoneNumber: "#frt-phone-number",
  ProSummery: 'input[name$="am_sub_heading"]',
  AboutMe: ":nth-child(7) > .form-control",
  DRSideSaveBtn: ".frt-save-button",
};
